//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"1\":\"helo\",\"12\":\"d\",\"123\":\"123\",\"1234\":\"helo\",\"12345\":\"helo\",\"123456\":\"helo\",\"12" +
            "34567\":\"helo\",\"12345678\":\"helo\",\"123456789\":\"helo\",\"1234567890\":\"helo\"}")]
        public string Aliases {
            get {
                return ((string)(this["Aliases"]));
            }
            set {
                this["Aliases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Modded_Editor {
            get {
                return ((bool)(this["Modded_Editor"]));
            }
            set {
                this["Modded_Editor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"plugins\":[]}")]
        public string Plugin_List {
            get {
                return ((string)(this["Plugin_List"]));
            }
            set {
                this["Plugin_List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public int Projects_Created {
            get {
                return ((int)(this["Projects_Created"]));
            }
            set {
                this["Projects_Created"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1876")]
        public int Projects_Played {
            get {
                return ((int)(this["Projects_Played"]));
            }
            set {
                this["Projects_Played"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("312")]
        public int Users_Viewed {
            get {
                return ((int)(this["Users_Viewed"]));
            }
            set {
                this["Users_Viewed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int User_Id {
            get {
                return ((int)(this["User_Id"]));
            }
            set {
                this["User_Id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Is_Setup {
            get {
                return ((bool)(this["Is_Setup"]));
            }
            set {
                this["Is_Setup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long Seconds_Spent {
            get {
                return ((long)(this["Seconds_Spent"]));
            }
            set {
                this["Seconds_Spent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long Start_Timestamp {
            get {
                return ((long)(this["Start_Timestamp"]));
            }
            set {
                this["Start_Timestamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long Time_Saved {
            get {
                return ((long)(this["Time_Saved"]));
            }
            set {
                this["Time_Saved"] = value;
            }
        }
    }
}
